# Generated by Django 2.1.3 on 2018-11-28 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='pile.Post'),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('post', 'author')},
        ),
    ]
