# Generated by Django 2.1.3 on 2018-11-28 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pile', '0002_auto_20181128_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=None, unique=True),
        ),
    ]
