# Generated by Django 2.1.3 on 2018-11-29 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pile', '0006_auto_20181129_1924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='favorite_posts',
            new_name='favorited_users',
        ),
    ]
