# Generated by Django 2.1.3 on 2018-11-30 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pile', '0004_auto_20181129_2236'),
        ('pile', '0008_auto_20181129_1928'),
    ]

    operations = [
    ]
