# Generated by Django 2.1.3 on 2018-11-30 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pile', '0009_merge_20181130_0117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='new_comment',
        ),
    ]
