# Generated by Django 2.1.3 on 2018-11-30 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pile', '0011_auto_20181130_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.URLField(blank=True, default=3333, unique=True),
            preserve_default=False,
        ),
    ]
