# Generated by Django 2.1.3 on 2018-11-30 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pile', '0014_auto_20181130_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
