# Generated by Django 2.1.3 on 2018-12-03 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pile', '0016_auto_20181203_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='new_comment',
            field=models.TextField(max_length=1000, verbose_name=''),
        ),
    ]
